name : Auto Merge Main to Testing Branch
on :
  push:
    branches:
      -main
jobs:
  merge:
    runs-on: ubuntu-latest
  steps:
    - name: Check The repo
      uses: action/checkout@v3
    - name : Config Git
      run:
       git config --global user.name 'RaneshKonni'
       git config --global user.email 'konniranesh03@gmail.com'

    - name: Fetch all branches
      run: git fetch --all

    - name: Merge main into testing
      run:
      git checkout testing
      git merge main --allow-unrelated-histories           
      git push origin testing